/**
 * Observers in Rami committees
 * API providing data for observers in Rami committees
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: ronitb@kkl.org.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of decision in committee
 */
export interface CommitteeStatus { 
    StatusId?: number | null;
    StatusName?: string;
}

