/**
 * Observers in Rami committees
 * API providing data for observers in Rami committees
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: ronitb@kkl.org.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObserverOption } from './observerOption';
import { RegionOption } from './regionOption';
import { RemiFileOption } from './remiFileOption';
import { TabaOption } from './tabaOption';
import { GushOption } from './gushOption';
import { ChelkaOption } from './chelkaOption';
import { MigrashOption } from './migrashOption';


/**
 * this object contains all the parameter values as presented in the XD (with autoComlete instead of textBox)
 */
export interface ObserversCommitteesSearchOption { 
    /**
     * free search ....
     */
    SearchStr?: string;
    /**
     * the Id of the Committee if known. This will end the search
     */
    CommitteeId?: number;
    RemiFileOption?: RemiFileOption;
    GushOption?: GushOption;
    ChelkaOption?: ChelkaOption;
    ObserverOption?: ObserverOption;
    MigrashOption?: MigrashOption;
    TabaOption?: TabaOption;
    RegionOption?: RegionOption;
}

