/**
 * Observers in Rami committees
 * API providing data for observers in Rami committees
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: ronitb@kkl.org.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObserverPosition } from './observerPosition';
import { CommitteeStatus } from './committeeStatus';


/**
 * this object contains a Remi File record
 */
export interface RemiFile { 
    /**
     * Remi File num
     */
    RemiFileNum?: number;
    /**
     * Num of assets per Remi file
     */
    AssetsCount?: number;
    /**
     * monetary value discussed in current committee
     */
    MonetaryValue?: number;
    CommitteeStatus?: CommitteeStatus;
    ObserverPosition?: ObserverPosition;
}

