/**
 * Observers in Rami committees
 * API providing data for observers in Rami committees
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: ronitb@kkl.org.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RemiFileOption { 
    /**
     * Remi file Id
     */
    value: number;
    /**
     * this is what you see in the Remi File option list
     */
    label: string;
    /**
     * selected item.
     */
    selected?: boolean;
    /**
     * disabled item.
     */
    disabled?: boolean;
}

