/**
 * Observers in Rami committees
 * API providing data for observers in Rami committees
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: ronitb@kkl.org.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObserverOption } from './observerOption';
import { RegionOption } from './regionOption';
import { RemiFileOption } from './remiFileOption';
import { TabaOption } from './tabaOption';
import { GushOption } from './gushOption';
import { ChelkaOption } from './chelkaOption';
import { MigrashOption } from './migrashOption';


export interface SearchOptionLookup { 
    remiOptions?: Array<RemiFileOption>;
    gushOptions?: Array<GushOption>;
    chelkaOptions?: Array<ChelkaOption>;
    observerOptions?: Array<ObserverOption>;
    migrashNumOptions?: Array<MigrashOption>;
    tabaNumOptions?: Array<TabaOption>;
    regionOptions?: Array<RegionOption>;
}

