export interface RootObject {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  gender: string;
  city: string;
  date: string;
  currency: string;
}

export const DEMO_DATA: RootObject[] = [
  {
    id: 1,
    first_name: 'Harold',
    last_name: 'Bouchier',
    email: 'hbouchier0@cbc.ca',
    gender: 'Male',
    city: 'Kanturk',
    date: '9/13/2021',
    currency: 'EUR',
  },
  {
    id: 2,
    first_name: 'Gustaf',
    last_name: 'Vanyukov',
    email: 'gvanyukov1@ning.com',
    gender: 'Male',
    city: 'Tupsan',
    date: '10/28/2021',
    currency: 'PHP',
  },
  {
    id: 3,
    first_name: 'Zebadiah',
    last_name: 'Finlow',
    email: 'zfinlow2@ted.com',
    gender: 'Female',
    city: 'Nanqiao',
    date: '1/7/2022',
    currency: 'CNY',
  },
  {
    id: 4,
    first_name: 'Olivier',
    last_name: 'Burhouse',
    email: 'oburh343434ouse3@mediafire.com',
    gender: 'Male',
    city: 'Novo',
    date: '11/23/2021',
    currency: 'EUR',
  },
  {
    id: 5,
    first_name: 'Winifield',
    last_name: 'Van Dalen',
    email: 'wvandalen4@exblog.jp',
    gender: 'Female',
    city: 'Si Khoraphum',
    date: '12/18/2021',
    currency: 'THB',
  },
  // {
  //   id: 6,
  //   first_name: 'Tadd',
  //   last_name: 'Vowles',
  //   email: 'tvowles5@rakuten.co.jp',
  //   gender: 'Female',
  //   city: 'Miaojie',
  //   date: '1/11/2022',
  //   currency: 'CNY',
  // },
  // {
  //   id: 7,
  //   first_name: 'Massimo',
  //   last_name: 'Willoughley',
  //   email: 'mwilloughley6@theglobeandmail.com',
  //   gender: 'Male',
  //   city: 'Qingyang',
  //   date: '1/28/2022',
  //   currency: null,
  // },
  // {
  //   id: 8,
  //   first_name: 'Ring',
  //   last_name: 'Otteridge',
  //   email: 'rotteridge7@harvard.edu',
  //   gender: 'Female',
  //   city: 'Limoges',
  //   date: '11/30/2021',
  //   currency: 'EUR',
  // },
  // {
  //   id: 9,
  //   first_name: 'Bartholomeus',
  //   last_name: 'Andreolli',
  //   email: 'bandreolli8@jimdo.com',
  //   gender: 'Male',
  //   city: 'Foxrock',
  //   date: '8/14/2021',
  //   currency: 'EUR',
  // },
  // {
  //   id: 10,
  //   first_name: 'Corby',
  //   last_name: 'Decayette',
  //   email: 'cdecayette9@microsoft.com',
  //   gender: 'Female',
  //   city: 'Naagas',
  //   date: '3/31/2021',
  //   currency: null,
  // },
  // {
  //   id: 11,
  //   first_name: 'Madelon',
  //   last_name: 'Aughtie',
  //   email: 'maughtiea@europa.eu',
  //   gender: 'Male',
  //   city: 'Williston',
  //   date: '6/27/2021',
  //   currency: 'ZAR',
  // },
  // {
  //   id: 12,
  //   first_name: 'Abigael',
  //   last_name: 'Gillease',
  //   email: 'agilleaseb@pcworld.com',
  //   gender: 'Male',
  //   city: 'Fruitvale',
  //   date: '6/21/2021',
  //   currency: 'CAD',
  // },
  // {
  //   id: 13,
  //   first_name: 'Eva',
  //   last_name: 'Swynfen',
  //   email: 'eswynfenc@ask.com',
  //   gender: 'Male',
  //   city: 'Bộc Bố',
  //   date: '3/19/2021',
  //   currency: 'VND',
  // },
  // {
  //   id: 14,
  //   first_name: 'Walden',
  //   last_name: 'Ridwood',
  //   email: 'wridwoodd@ted.com',
  //   gender: 'Male',
  //   city: 'Tabālah',
  //   date: '10/4/2021',
  //   currency: null,
  // },
  // {
  //   id: 15,
  //   first_name: 'Kellyann',
  //   last_name: 'Swadden',
  //   email: 'kswaddene@latimes.com',
  //   gender: 'Male',
  //   city: 'Bol’shoy Karay',
  //   date: '2/2/2022',
  //   currency: 'RUB',
  // },
  // {
  //   id: 16,
  //   first_name: 'Allin',
  //   last_name: 'Lishman',
  //   email: 'alishmanf@thetimes.co.uk',
  //   gender: 'Genderfluid',
  //   city: 'Jangkat',
  //   date: '8/10/2021',
  //   currency: null,
  // },
  // {
  //   id: 17,
  //   first_name: 'Burnaby',
  //   last_name: 'Amber',
  //   email: 'bamberg@latimes.com',
  //   gender: 'Female',
  //   city: 'Roches Noire',
  //   date: '9/9/2021',
  //   currency: 'MUR',
  // },
  // {
  //   id: 18,
  //   first_name: 'Liva',
  //   last_name: 'McNeigh',
  //   email: 'lmcneighh@arstechnica.com',
  //   gender: 'Bigender',
  //   city: 'Carmen',
  //   date: '8/10/2021',
  //   currency: null,
  // },
  // {
  //   id: 19,
  //   first_name: 'Marlyn',
  //   last_name: 'Rosling',
  //   email: 'mroslingi@lycos.com',
  //   gender: 'Male',
  //   city: 'Staryy Togul',
  //   date: '8/17/2021',
  //   currency: 'RUB',
  // },
  // {
  //   id: 20,
  //   first_name: 'Janaye',
  //   last_name: 'Barcke',
  //   email: 'jbarckej@g.co',
  //   gender: 'Female',
  //   city: 'Bořitov',
  //   date: '10/4/2021',
  //   currency: 'CZK',
  // },
];
